kotlin.code.style=official
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin Multiplatform — allow configuring iOS targets on non-mac hosts (they just won't compile)
kotlin.native.ignoreDisabledTargets=true
